name: Development branches

on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and run tests on JDK 17
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Expose branch name
        run: echo ${{ github.ref }}

      # Setup JDK and Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          cache: maven
          java-version: 17
          server-id: ossrh
          server-username: OSS_CENTRAL_USERNAME # env variable for Maven Central
          server-password: OSS_CENTRAL_PASSWORD # env variable for Maven Central

      # Prepare
      - name: Prepare Maven Wrapper
        run: chmod +x ./mvnw

      # Build
      - name: Build with Maven
        run: ./mvnw clean verify -U -B -T4 -ntp

      - name: Upload coverage to Codecov
        if: github.event_name == 'push' && github.actor != 'dependabot[bot]'
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV_TOKEN}}
